# https://goreleaser.com
version: 2

project_name: chain-blackbox-exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    main: .
    binary: 'chain-blackbox-exporter-{{ .Os }}-{{ .Arch }}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

# Upload binaries as-is (no archive); name_template is used for Release asset filenames
archives:
  - formats: [ 'binary' ]
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^Merge "
